apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: agrius-rehydrate-{{idx}}
spec:
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 2
  concurrencyPolicy: Replace
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: agrius-rehydrate
            image: agriuseatstweets/rehydrate:0.0.14
            terminationMessagePolicy: FallbackToLogsOnError
            resources:
              requests:
                memory: "256Mi"
            envFrom:
            - secretRef:
                name: agrius-rehydrate-envs
            env:
              - name: KAFKA_BROKERS
                value: "hydra-kafka:9092"
              - name: KAFKA_POLL_INTERVAL
                value: "360000"
              - name: REHYDRATE_TOPIC
                value: "ubdata"
              - name: PUB_TOPIC
                value: "tweets"
              - name: REHYDRATE_SIZE
                value: "90000"
              - name: BATCH_SIZE
                value: "2000"
              - name: T_ACCESS_TOKEN
                value: "{{token}}"
              - name: T_TOKEN_SECRET
                value: "{{secret}}"
