apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: agrius-rehydrate-{{idx}}
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: agrius-rehydrate
            image: agriuseatstweets/rehydrate:0.0.6
            resources:
              requests:
                memory: "128Mi"
            envFrom:
            - secretRef:
                name: agrius-rehydrate-envs
            env:
              - name: KAFKA_BROKERS
                value: "kafka:9092"
              - name: REHYDRATE_TOPIC
                value: "ubdata"
              - name: PUB_TOPIC
                value: "tweets"
              - name: REHYDRATE_SIZE
                value: "90000"
              - name: T_ACCESS_TOKEN
                value: "{{token}}"
              - name: T_TOKEN_SECRET
                value: "{{secret}}"
